type Task = {
  taskStatus: string;
  staffName: string;
  serviceType: string;
  taskType: string;
  internalFrom: string;
  internalTo: string;
  requestDateTime: string;
  taskID: string;
  instructions?: string;
  items?: {
    shampoo?: number;
    conditioner?: number;
    towel?: number;
  };
};

const dummyData: Task[] = [
  {
    taskStatus: "not accepted",
    staffName: "Jane Smith",
    serviceType: "Routine Cleaning",
    taskType: "Guest",
    internalFrom: "Pantry",
    internalTo: "Reception",
    requestDateTime: "2024-04-07T10:30:00",
    taskID: "987654321",
    instructions: "Please also provide shampoo, conditioner, and towels.",
    items: {
      shampoo: 1,
      conditioner: 1,
      towel: 2,
    },
  },
  {
    taskStatus: "not accepted",
    staffName: "John Doe",
    serviceType: "Deep Cleaning",
    taskType: "Guest",
    internalFrom: "Room",
    internalTo: "Laundry",
    requestDateTime: "2024-04-08T09:45:00",
    taskID: "123456789",
    items: {
      shampoo: 1,
      conditioner: 1,
      towel: 2,
    },
  },
  {
    taskStatus: "accepted",
    staffName: "Alice Johnson",
    serviceType: "Maintenance",
    taskType: "Repair",
    internalFrom: "Maintenance Room",
    internalTo: "Suite 101",
    requestDateTime: "2024-04-09T14:20:00",
    taskID: "987654322",
    instructions: "Check for plumbing leaks and fix if any.",
  },
  {
    taskStatus: "accepted",
    staffName: "David Brown",
    serviceType: "Housekeeping",
    taskType: "Room Cleaning",
    internalFrom: "Housekeeping Cart",
    internalTo: "Suite 203",
    requestDateTime: "2024-04-10T11:00:00",
    taskID: "987654323",
    items: {
      shampoo: 1,
      conditioner: 1,
      towel: 2,
    },
  },
  {
    taskStatus: "accepted",
    staffName: "Emily White",
    serviceType: "Room Service",
    taskType: "Food Delivery",
    internalFrom: "Kitchen",
    internalTo: "Suite 301",
    requestDateTime: "2024-04-11T18:30:00",
    taskID: "987654324",
    instructions: "Deliver dinner for two.",
    items: {
      shampoo: 1,
      conditioner: 1,
      towel: 2,
    },
  },
  {
    taskStatus: "completed",
    staffName: "Michael Green",
    serviceType: "Routine Cleanup",
    taskType: "Internal",
    internalFrom: "pantry",
    internalTo: "Room 102",
    requestDateTime: "2024-04-12T21:00:00",
    taskID: "987654325",
  },
  {
    taskStatus: "ongoing",
    staffName: "Sarah Taylor",
    serviceType: "Concierge",
    taskType: "Guest Assistance",
    internalFrom: "Front Desk",
    internalTo: "Lobby",
    requestDateTime: "2024-04-13T16:15:00",
    taskID: "987654326",
    instructions: "Assist with luggage.",
  },
  {
    taskStatus: "ongoing",
    staffName: "Robert Wilson",
    serviceType: "Valet",
    taskType: "Car Parking",
    internalFrom: "Valet Stand",
    internalTo: "Parking Garage",
    requestDateTime: "2024-04-14T08:00:00",
    taskID: "987654327",
  },
  {
    taskStatus: "delayed",
    staffName: "Jessica Lee",
    serviceType: "Spa",
    taskType: "Massage",
    internalFrom: "Spa Reception",
    internalTo: "Treatment Room",
    requestDateTime: "2024-04-15T13:30:00",
    taskID: "987654328",
    instructions: "Prepare massage room with scented candles and soft music.",
  },
  {
    taskStatus: "delayed",
    staffName: "Daniel Harris",
    serviceType: "Maintenance",
    taskType: "HVAC Repair",
    internalFrom: "Maintenance Room",
    internalTo: "Suite 405",
    requestDateTime: "2024-04-16T10:00:00",
    taskID: "987654329",
    instructions:
      "Check air conditioning unit for malfunction and repair as needed.",
  },

  {
    taskStatus: "accepted",
    staffName: "Jane Smith",
    serviceType: "Routine Cleaning",
    taskType: "Guest",
    internalFrom: "Pantry",
    internalTo: "Reception",
    requestDateTime: "2024-04-07T10:30:00",
    taskID: "987654321",
    instructions: "Please also provide shampoo, conditioner, and towels.",
    items: {
      shampoo: 1,
      conditioner: 1,
      towel: 2,
    },
  },
  {
    taskStatus: "accepted",
    staffName: "John Doe",
    serviceType: "Deep Cleaning",
    taskType: "Guest",
    internalFrom: "Room",
    internalTo: "Laundry",
    requestDateTime: "2024-04-08T09:45:00",
    taskID: "123456789",
    items: {
      shampoo: 1,
      conditioner: 1,
      towel: 2,
    },
  },
  {
    taskStatus: "completed",
    staffName: "Alice Johnson",
    serviceType: "Maintenance",
    taskType: "Repair",
    internalFrom: "Maintenance Room",
    internalTo: "Suite 101",
    requestDateTime: "2024-04-09T14:20:00",
    taskID: "987654322",
    instructions: "Check for plumbing leaks and fix if any.",
  },
  {
    taskStatus: "not accepted",
    staffName: "David Brown",
    serviceType: "Housekeeping",
    taskType: "Room Cleaning",
    internalFrom: "Housekeeping Cart",
    internalTo: "Suite 203",
    requestDateTime: "2024-04-10T11:00:00",
    taskID: "987654323",
    items: {
      shampoo: 1,
      conditioner: 1,
      towel: 2,
    },
  },
  {
    taskStatus: "not accepted",
    staffName: "Emily White",
    serviceType: "Room Service",
    taskType: "Food Delivery",
    internalFrom: "Kitchen",
    internalTo: "Suite 301",
    requestDateTime: "2024-04-11T18:30:00",
    taskID: "987654324",
    instructions: "Deliver dinner for two.",
    items: {
      shampoo: 1,
      conditioner: 1,
      towel: 2,
    },
  },
  {
    taskStatus: "completed",
    staffName: "Michael Green",
    serviceType: "Routine Cleanup",
    taskType: "Internal",
    internalFrom: "pantry",
    internalTo: "Room 102",
    requestDateTime: "2024-04-12T21:00:00",
    taskID: "987654325",
  },
  {
    taskStatus: "ongoing",
    staffName: "Sarah Taylor",
    serviceType: "Concierge",
    taskType: "Guest Assistance",
    internalFrom: "Front Desk",
    internalTo: "Lobby",
    requestDateTime: "2024-04-13T16:15:00",
    taskID: "987654326",
    instructions: "Assist with luggage.",
  },
  {
    taskStatus: "delayed",
    staffName: "Robert Wilson",
    serviceType: "Valet",
    taskType: "Car Parking",
    internalFrom: "Valet Stand",
    internalTo: "Parking Garage",
    requestDateTime: "2024-04-14T08:00:00",
    taskID: "987654327",
  },
  {
    taskStatus: "delayed",
    staffName: "Jessica Lee",
    serviceType: "Spa",
    taskType: "Massage",
    internalFrom: "Spa Reception",
    internalTo: "Treatment Room",
    requestDateTime: "2024-04-15T13:30:00",
    taskID: "987654328",
    instructions: "Prepare massage room with scented candles and soft music.",
  },
  {
    taskStatus: "completed",
    staffName: "Daniel Harris",
    serviceType: "Maintenance",
    taskType: "HVAC Repair",
    internalFrom: "Maintenance Room",
    internalTo: "Suite 405",
    requestDateTime: "2024-04-16T10:00:00",
    taskID: "987654329",
    instructions:
      "Check air conditioning unit for malfunction and repair as needed.",
  },
];

export default dummyData;
